---
title: "My First Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data("instacart") 
instacart = 
  instacart %>% 
  filter(department == "dairy eggs")

```



Column {data-width=600}
-----------------------------------------------------------------------

### Figure 1. refrigerated pudding desserts aisle: Days since prior order vs Order number

```{r}
instacart %>%
  filter(aisle == "refrigerated pudding desserts" & user_id < 4000) %>% 
  mutate(text_label = str_c("Days since prior order:", days_since_prior_order, '\nOrder number: ', order_number)) %>% 
  plot_ly(
    x = ~order_number, y = ~days_since_prior_order, type = "scatter", mode = "markers",
    color = ~product_name, text = ~text_label, alpha = 0.5)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Figure 2. aisle order numbers (when days since prior order is zero)

```{r}
instacart %>% 
  filter(days_since_prior_order == 0) %>% 
  mutate(aisle = fct_reorder((aisle), order_number)) %>% 
  plot_ly(y = ~order_number, color = ~aisle, type = "box", 
          colors = "Set2")
```

### Figure 3. aisle numbers

```{r}
instacart %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar")
```

